version: "3.9"

services:
  db:
    image: "postgres"
    container_name: "nv-postgres-dev"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"